### ISSUE TITLE
Container does not start - npm install missing in Dockerfile

### ISSUE THREAD

**Issue by domkun** [adrianrudnik/mjml-server#23]
The latest tag and the 2.5.0 tag does not start anymore.

In the commit [20f67cfa8087c4f97ff08d7da9f1702d627f6aef](https://github.com/adrianrudnik/mjml-server/commit/20f67cfa8087c4f97ff08d7da9f1702d627f6aef), besides removing `curl` and `ca-certificates` also the `npm install` command was removed.

Readding `npm install` in the Dockerfile should fix that.

**Comment by adrianrudnik** [comment]
Oh boy, that is correct, had a strange side effect with QEMU and that lead to this bad decision. Fixed, pushed as 2.5.0 and 2.5.1, can you try again?

**Comment by domkun** [comment]
Starts just fine now. Thanks for the quick fix.
